apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

namespace: cloud-platform-dev

images:
  - name: backend
    newName: 930067562644.dkr.ecr.us-east-1.amazonaws.com/cloud-platform-dev-backend
    newTag: c08b09685416445e9286a772bb480b7703dd163a

  - name: frontend
    newName: 930067562644.dkr.ecr.us-east-1.amazonaws.com/cloud-platform-dev-frontend
    newTag: c08b09685416445e9286a772bb480b7703dd163a