apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

namespace: cloud-platform-dev

images:
  - name: backend
    newName: 930067562644.dkr.ecr.us-east-1.amazonaws.com/cloud-platform-dev-backend
    newTag: 5736979da892224dd6108e5c64b5d976db36065d

  - name: frontend
    newName: 930067562644.dkr.ecr.us-east-1.amazonaws.com/cloud-platform-dev-frontend
    newTag: 5736979da892224dd6108e5c64b5d976db36065d