apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

namespace: cloud-platform-dev

images:
  - name: backend
    newName: 930067562644.dkr.ecr.us-east-1.amazonaws.com/cloud-platform-dev-backend
    newTag: 65df8de3b0c22f715cdd0476bdc298a9a8490cf5

  - name: frontend
    newName: 930067562644.dkr.ecr.us-east-1.amazonaws.com/cloud-platform-dev-frontend
    newTag: 65df8de3b0c22f715cdd0476bdc298a9a8490cf5