name: Build and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Use OIDC (NO secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::930067562644:role/cloud-platform-dev-github-actions-ci
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      # 🔥 Backend
      - name: Build & push backend
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t 930067562644.dkr.ecr.us-east-1.amazonaws.com/cloud-platform-dev-backend:${{ steps.vars.outputs.TAG }} \
            --push ./services/backend

      # 🔥 Frontend
      - name: Build & push frontend
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t 930067562644.dkr.ecr.us-east-1.amazonaws.com/cloud-platform-dev-frontend:${{ steps.vars.outputs.TAG }} \
            --push ./services/frontend